SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [rpt].[vw_Steelers_500f_ExcludeEvents]

AS 

SELECT DISTINCT loyalty_event_id
FROM ods.Steelers_500f_Events
WHERE detail IN (  'Earned a 2015-16 Wild Card Badge badge'
				  ,'Earned a playoff Clincher Badge badge'
				  ,'Earned a thank you fans badge'
				  ,'Earned a record breaker badge')
OR type IN (
 '2014_season_tickets'
,'2015_division_round'
,'9202015'
,'Adjustment'
,'Customer_service'
,'deal'
,'division_winner_2014'
,'downgrade_tier'
,'email'
,'enrollment'
,'Expiration'
,'expire_tier'
,'facebook_boost'
,'gift'
,'instagram_boost'
,'nov2_joe_greene_game'
,'nov30_anniversary'
,'onthefield_dec_20'
,'onthefield_dec_6'
,'onthefield_dec21'
,'onthefield_dec28'
,'onthefield_nov_1'
,'onthefield_nov_15'
,'onthefield_nov_8'
,'onthefield_oct_1'
,'onthefield_oct_18'
,'onthefield_sep_20'
,'players_tunnel'
,'players_tunnel_dec21'
,'players_tunnel_dec28'
,'players_tunnel_jan_3'
,'players_tunnel_nov_2'
,'players_tunnel_nov30'
,'players_tunneldec_20'
,'players_tunneldec_6'
,'players_tunnelnov_1'
,'players_tunnelnov_15'
,'players_tunnelnov_8'
,'players_tunneloct_1'
,'players_tunneloct_18'
,'players_tunnelsep_20'
,'playoff_clinch_2014'
,'pregate_photo'
,'profile_bonus'
,'record_holder_event'
,'reward'
,'rewarded_dec28'
,'rewarded_jan_3'
,'season_ticket_holder'
,'sth_2017'
,'sth_wait_list'
,'surprise_delight'
,'surprise_delight2016'
,'surprise_delight2017'
,'TESTEVENT'
,'TESTEVENT2'
,'thank_you_dec28'
,'tier'
,'towel_twirl'
,'towel_twirl_dec_20'
,'towel_twirl_dec21'
,'towel_twirl_dec28'
,'towel_twirl_jan_3'
,'towel_twirl_nov_1'
,'towel_twirl_nov_15'
,'towel_twirl_nov_2'
,'towel_twirl_nov_8'
,'towel_twirl_nov30'
,'towel_twirl_oct_18'
,'towel_twirl_sep_20'
,'towel_unfurl'
,'towel_unfurl_dec_20'
,'towel_unfurl_dec_6'
,'towel_unfurl_dec21'
,'towel_unfurl_dec28'
,'towel_unfurl_nov_1'
,'towel_unfurl_nov_15'
,'towel_unfurl_nov_2'
,'towel_unfurl_nov30'
,'towel_unfurl_oct_1'
,'towel_unfurl_oct_18'
,'towel_unfurl_sep_20'
,'travel_nation_dec20'
,'travel_nation_dec6'
,'travel_nation_nov1'
,'travel_nation_nov15'
,'travel_nation_nov8'
,'travel_nation_oct1'
,'travel_nation_oct18'
,'travel_nation_sep20'
,'twitter_boost'
,'upgrade_tier')
GO
