SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE PROCEDURE [etl].[Load_ods_FanCentric_Customers]
(
	@BatchId INT = 0,
	@Options NVARCHAR(MAX) = null
)
AS 

BEGIN
/**************************************Comments***************************************
**************************************************************************************
Mod #:  1
Name:     dbo
Date:     09/22/2017
Comments: Initial creation
*************************************************************************************/

DECLARE @RunTime DATETIME = GETDATE()


DECLARE @ExecutionId uniqueidentifier = newid();
DECLARE @ProcedureName nvarchar(255) = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID);
DECLARE @SrcRowCount int = ISNULL((SELECT CONVERT(varchar, COUNT(*)) FROM stg.FanCentric_Customers),'0');	
DECLARE @SrcDataSize NVARCHAR(255) = '0'


/*Load Options into a temp table*/
SELECT Col1 AS OptionKey, Col2 as OptionValue INTO #Options FROM [dbo].[SplitMultiColumn](@Options, '=', ';')


/*Extract Options, default values set if the option is not specified*/	
DECLARE @DisableInsert nvarchar(5) = ISNULL((SELECT OptionValue FROM #Options WHERE OptionKey = 'DisableInsert'),'false')
DECLARE @DisableUpdate nvarchar(5) = ISNULL((SELECT OptionValue FROM #Options WHERE OptionKey = 'DisableUpdate'),'false')
DECLARE @DisableDelete nvarchar(5) = ISNULL((SELECT OptionValue FROM #Options WHERE OptionKey = 'DisableDelete'),'true')


BEGIN TRY 


PRINT 'Execution Id: ' + CONVERT(NVARCHAR(100),@ExecutionId)


EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Procedure Processing', 'Start', @ExecutionId
EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Src Row Count', @SrcRowCount, @ExecutionId
EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Src DataSize', @SrcDataSize, @ExecutionId


SELECT CAST(NULL AS BINARY(32)) ETL_DeltaHashKey
,  ETL_FileName, CUST_ID, EMAIL_ID, EMAIL_ADDR, EMAILABLE_FLG, USERNAME, ADDR_ID, INDIV_ID, FAV_TEAM_CD, TEAM_LONG_NM, GENDER, FIRST_NM, LAST_NM, MIDDLE_NM, ACE_PRIM_ADDR, ACE_SEC_ADDR, ACE_CITY, ACE_STATE, ACE_POSTAL_CODE, ACE_ISO_CODE, BIRTH_DT, AGE, ORIG_SRC, ORIG_SRC_DT, ORIG_SRC_BU, ORIG_EPS_FCM_CRTD_DT, IN_MARKET_CD, BU_CLUBS_FLG, BU_DCOM_FLG, BU_LIVE_EVENT_FLG, BU_PRTR_FLG, BU_SHOP_FLG, BU_YUTH_FLG, BU_INTL_FLG, BU_OTHR_FLG, BU_MKTG_FLG, JETS_CROSSOVER_FLG, CROSSOVER_BU_CD, CROSSOVER_PRODUCT_CD, LST_FANTASY_SSN, LST_FANT_LM_SSN, LST_FANT_UE_SSN, LST_FANT_CUSTOM_SSN, LST_FANT_MANAGED_SSN, LST_SUB_PROD, LST_SUB_PROD_SSN, LST_GPD_SUB_SSN, LST_GPD_FT_SSN, LST_GPI_SUB_SSN, LST_GPI_FT_SSN, LST_GPI_SUB_SSN_SSN_FLG, LST_GPI_SUB_SSNPLS_SSN_FLG, LST_GPI_SUB_WKLY_SSN_FLG, LST_GPI_SUB_FYT_SSN_FLG, LST_NFL_NOW_SIGNUP_DT, LST_MINIGM_SSN, LST_MINIGM_SSN_REG_DT, LST_PERFCH_SSN, LST_PERFCH_SSN_REG_DT, LST_PLAYCH_SSN, LST_PLAYCH_SSN_REG_DT, LST_PICKEM_SSN, LST_PICKEM_SSN_REG_DT, LST_PTP_SSN, LST_PTP_SSN_REG_DT, LST_DRAFT_FMP_SSN, LST_KICKOFF_FMP_SSN, LST_SB_FMP_SSN, LST_PB_STH_SSN, LST_PB_STB_SSN, SHOP_LST_PURCH_DT, SHOP_DOL_3M, SHOP_DOL_6M, SHOP_DOL_1YR, SHOP_DOL_TOTAL, SHOP_ORD_TOTAL, SHOP_LST_CANCER_PURCH_DT, SHOP_CANCER_PURCHASES, SHOP_CANCER_DOL, SHOP_LST_BT_PURCH_DT, SHOP_BT_PURCHASES, SHOP_BT_DOL, SHOP_LST_JERSEYS_PURCH_DT, SHOP_JERSEYS_PURCHASES, SHOP_JERSEYS_DOL, SHOP_LST_HOMEOFF_PURCH_DT, SHOP_HOMEOFF_PURCHASES, SHOP_HOMEOFF_DOL, SHOP_LST_MENS_PURCH_DT, SHOP_MENS_PURCHASES, SHOP_MENS_DOL, SHOP_LST_PLUS_PURCH_DT, SHOP_PLUS_PURCHASES, SHOP_PLUS_DOL, SHOP_LST_YOUTH_PURCH_DT, SHOP_YOUTH_PURCHASES, SHOP_YOUTH_DOL, SHOP_LST_WOMENS_PURCH_DT, SHOP_WOMENS_PURCHASES, SHOP_WOMENS_DOL, SHOP_LST_UNDERMINED_PURCH_DT, SHOP_UNDERMINED_PURCHASES, SHOP_UNDERMINED_DOL, ACTIVE_0_3M_FLAG, ACTIVE_4_6M_FLAG, ACTIVE_7_12M_FLAG, ACTIVE_1YR_FLAG, ACTIVE_2YR_FLAG, ACTIVE_3YR_FLAG, CUST_RECENCY_DT, EM_LST_OPEN_DT, EM_LST_DCOM_OPEN_DT, EM_LST_MOBILE_OPEN_DT, EM_LST_SMRTPH_OPEN_DT, EM_LST_TABLT_OPEN_DT, EM_LST_CLICK_DT, EM_LST_DCOM_CLICK_DT, EM_LST_MOBILE_CLICK_DT, EM_LST_SMRTPH_CLICK_DT, EM_LST_TABLT_CLICK_DT, WEB_LST_VST_DT, APP_LST_VST_DT, FANTASY_LST_VST_DT, LST_M_FANTASY_VST_DT, CURR_SSN_WEB_PAGEVIEWS, CURR_SSN_FANTASY_PAGEVIEWS, CURR_SSN_APP_VISITS, CURR_SSN_M_FANTASY_PAGEVIEWS, PREV_SSN_WEB_PAGEVIEWS, PREV_SSN_FANTASY_PAGEVIEWS, PREV_SSN_APP_VISITS, PREV_SSN_M_FANTASY_PAGEVIEWS, TOTAL_SSN_WEB_PAGEVIEWS, TOTAL_CURR_SSN_FANTASY_PAGEVW, TOTAL_CURR_SSN_APP_VISITS, TOTAL_CURR_SSN_M_FANT_PAGEVW, LST_CLUBS_STH_SSN, LST_CLUBS_STB_SSN, CLUBS_STB_TIX_REV, CLUBS_STB_TIX_ORDERS, CLUBS_STB_TIX_LST_DT, CLUBS_STB_NUMSEATS, LST_TICKET_EXCH_SSN, TICKET_EXCH_REV, TICKET_EXCH_ORDERS, TICKET_EXCH_LST_DT, TICKET_EXCH_NUMSEATS, DTV_SUNDAY_TICKET_FLG, DTV_SUNDAY_TICKET_ACTIVE_FLG, DTV_TV_FLG, DTV_TV_ACTIVE_FLG, DTV_COMMERICAL_FLG, DTV_COMMERICAL_ACTIVE_FLG, MADDEN_PLAYER_FLG, NFLN_SURVEY_HAVE_FLG, NFLN_SURVEY_AWARE_FLG, GIGYA_FLG, SOCIAL_FACEBOOK_FLG, SOCIAL_GOOGLEPLUS_FLG, SOCIAL_MESSENGER_FLG, TRANSACTIONAL_VALUE, TRANSACTIONAL_VALUE_CURR_SSN, TRANSACTIONAL_VALUE_PREV_SSN, EPS_CRTD_DT
INTO #SrcData
FROM (
	SELECT  ETL_FileName, CUST_ID, EMAIL_ID, EMAIL_ADDR, EMAILABLE_FLG, USERNAME, ADDR_ID, INDIV_ID, FAV_TEAM_CD, TEAM_LONG_NM, GENDER, FIRST_NM, LAST_NM, MIDDLE_NM, ACE_PRIM_ADDR, ACE_SEC_ADDR, ACE_CITY, ACE_STATE, ACE_POSTAL_CODE, ACE_ISO_CODE, BIRTH_DT, AGE, ORIG_SRC, ORIG_SRC_DT, ORIG_SRC_BU, ORIG_EPS_FCM_CRTD_DT, IN_MARKET_CD, BU_CLUBS_FLG, BU_DCOM_FLG, BU_LIVE_EVENT_FLG, BU_PRTR_FLG, BU_SHOP_FLG, BU_YUTH_FLG, BU_INTL_FLG, BU_OTHR_FLG, BU_MKTG_FLG, JETS_CROSSOVER_FLG, CROSSOVER_BU_CD, CROSSOVER_PRODUCT_CD, LST_FANTASY_SSN, LST_FANT_LM_SSN, LST_FANT_UE_SSN, LST_FANT_CUSTOM_SSN, LST_FANT_MANAGED_SSN, LST_SUB_PROD, LST_SUB_PROD_SSN, LST_GPD_SUB_SSN, LST_GPD_FT_SSN, LST_GPI_SUB_SSN, LST_GPI_FT_SSN, LST_GPI_SUB_SSN_SSN_FLG, LST_GPI_SUB_SSNPLS_SSN_FLG, LST_GPI_SUB_WKLY_SSN_FLG, LST_GPI_SUB_FYT_SSN_FLG, LST_NFL_NOW_SIGNUP_DT, LST_MINIGM_SSN, LST_MINIGM_SSN_REG_DT, LST_PERFCH_SSN, LST_PERFCH_SSN_REG_DT, LST_PLAYCH_SSN, LST_PLAYCH_SSN_REG_DT, LST_PICKEM_SSN, LST_PICKEM_SSN_REG_DT, LST_PTP_SSN, LST_PTP_SSN_REG_DT, LST_DRAFT_FMP_SSN, LST_KICKOFF_FMP_SSN, LST_SB_FMP_SSN, LST_PB_STH_SSN, LST_PB_STB_SSN, SHOP_LST_PURCH_DT, SHOP_DOL_3M, SHOP_DOL_6M, SHOP_DOL_1YR, SHOP_DOL_TOTAL, SHOP_ORD_TOTAL, SHOP_LST_CANCER_PURCH_DT, SHOP_CANCER_PURCHASES, SHOP_CANCER_DOL, SHOP_LST_BT_PURCH_DT, SHOP_BT_PURCHASES, SHOP_BT_DOL, SHOP_LST_JERSEYS_PURCH_DT, SHOP_JERSEYS_PURCHASES, SHOP_JERSEYS_DOL, SHOP_LST_HOMEOFF_PURCH_DT, SHOP_HOMEOFF_PURCHASES, SHOP_HOMEOFF_DOL, SHOP_LST_MENS_PURCH_DT, SHOP_MENS_PURCHASES, SHOP_MENS_DOL, SHOP_LST_PLUS_PURCH_DT, SHOP_PLUS_PURCHASES, SHOP_PLUS_DOL, SHOP_LST_YOUTH_PURCH_DT, SHOP_YOUTH_PURCHASES, SHOP_YOUTH_DOL, SHOP_LST_WOMENS_PURCH_DT, SHOP_WOMENS_PURCHASES, SHOP_WOMENS_DOL, SHOP_LST_UNDERMINED_PURCH_DT, SHOP_UNDERMINED_PURCHASES, SHOP_UNDERMINED_DOL, ACTIVE_0_3M_FLAG, ACTIVE_4_6M_FLAG, ACTIVE_7_12M_FLAG, ACTIVE_1YR_FLAG, ACTIVE_2YR_FLAG, ACTIVE_3YR_FLAG, CUST_RECENCY_DT, EM_LST_OPEN_DT, EM_LST_DCOM_OPEN_DT, EM_LST_MOBILE_OPEN_DT, EM_LST_SMRTPH_OPEN_DT, EM_LST_TABLT_OPEN_DT, EM_LST_CLICK_DT, EM_LST_DCOM_CLICK_DT, EM_LST_MOBILE_CLICK_DT, EM_LST_SMRTPH_CLICK_DT, EM_LST_TABLT_CLICK_DT, WEB_LST_VST_DT, APP_LST_VST_DT, FANTASY_LST_VST_DT, LST_M_FANTASY_VST_DT, CURR_SSN_WEB_PAGEVIEWS, CURR_SSN_FANTASY_PAGEVIEWS, CURR_SSN_APP_VISITS, CURR_SSN_M_FANTASY_PAGEVIEWS, PREV_SSN_WEB_PAGEVIEWS, PREV_SSN_FANTASY_PAGEVIEWS, PREV_SSN_APP_VISITS, PREV_SSN_M_FANTASY_PAGEVIEWS, TOTAL_SSN_WEB_PAGEVIEWS, TOTAL_CURR_SSN_FANTASY_PAGEVW, TOTAL_CURR_SSN_APP_VISITS, TOTAL_CURR_SSN_M_FANT_PAGEVW, LST_CLUBS_STH_SSN, LST_CLUBS_STB_SSN, CLUBS_STB_TIX_REV, CLUBS_STB_TIX_ORDERS, CLUBS_STB_TIX_LST_DT, CLUBS_STB_NUMSEATS, LST_TICKET_EXCH_SSN, TICKET_EXCH_REV, TICKET_EXCH_ORDERS, TICKET_EXCH_LST_DT, TICKET_EXCH_NUMSEATS, DTV_SUNDAY_TICKET_FLG, DTV_SUNDAY_TICKET_ACTIVE_FLG, DTV_TV_FLG, DTV_TV_ACTIVE_FLG, DTV_COMMERICAL_FLG, DTV_COMMERICAL_ACTIVE_FLG, MADDEN_PLAYER_FLG, NFLN_SURVEY_HAVE_FLG, NFLN_SURVEY_AWARE_FLG, GIGYA_FLG, SOCIAL_FACEBOOK_FLG, SOCIAL_GOOGLEPLUS_FLG, SOCIAL_MESSENGER_FLG, TRANSACTIONAL_VALUE, TRANSACTIONAL_VALUE_CURR_SSN, TRANSACTIONAL_VALUE_PREV_SSN, EPS_CRTD_DT
	, ROW_NUMBER() OVER(PARTITION BY CUST_ID ORDER BY ETL_ID) RowRank
	FROM stg.FanCentric_Customers
) a
WHERE RowRank = 1


EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Src Table Setup', 'Temp Table Loaded', @ExecutionId


UPDATE #SrcData
SET ETL_DeltaHashKey = HASHBYTES('sha2_256', ISNULL(RTRIM(ACE_CITY),'DBNULL_TEXT') + ISNULL(RTRIM(ACE_ISO_CODE),'DBNULL_TEXT') + ISNULL(RTRIM(ACE_POSTAL_CODE),'DBNULL_TEXT') + ISNULL(RTRIM(ACE_PRIM_ADDR),'DBNULL_TEXT') + ISNULL(RTRIM(ACE_SEC_ADDR),'DBNULL_TEXT') + ISNULL(RTRIM(ACE_STATE),'DBNULL_TEXT') + ISNULL(RTRIM(ACTIVE_0_3M_FLAG),'DBNULL_TEXT') + ISNULL(RTRIM(ACTIVE_1YR_FLAG),'DBNULL_TEXT') + ISNULL(RTRIM(ACTIVE_2YR_FLAG),'DBNULL_TEXT') + ISNULL(RTRIM(ACTIVE_3YR_FLAG),'DBNULL_TEXT') + ISNULL(RTRIM(ACTIVE_4_6M_FLAG),'DBNULL_TEXT') + ISNULL(RTRIM(ACTIVE_7_12M_FLAG),'DBNULL_TEXT') + ISNULL(RTRIM(ADDR_ID),'DBNULL_TEXT') + ISNULL(RTRIM(AGE),'DBNULL_TEXT') + ISNULL(RTRIM(APP_LST_VST_DT),'DBNULL_TEXT') + ISNULL(RTRIM(BIRTH_DT),'DBNULL_TEXT') + ISNULL(RTRIM(BU_CLUBS_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(BU_DCOM_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(BU_INTL_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(BU_LIVE_EVENT_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(BU_MKTG_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(BU_OTHR_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(BU_PRTR_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(BU_SHOP_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(BU_YUTH_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(CLUBS_STB_NUMSEATS),'DBNULL_TEXT') + ISNULL(RTRIM(CLUBS_STB_TIX_LST_DT),'DBNULL_TEXT') + ISNULL(RTRIM(CLUBS_STB_TIX_ORDERS),'DBNULL_TEXT') + ISNULL(RTRIM(CLUBS_STB_TIX_REV),'DBNULL_TEXT') + ISNULL(RTRIM(CROSSOVER_BU_CD),'DBNULL_TEXT') + ISNULL(RTRIM(CROSSOVER_PRODUCT_CD),'DBNULL_TEXT') + ISNULL(RTRIM(CURR_SSN_APP_VISITS),'DBNULL_TEXT') + ISNULL(RTRIM(CURR_SSN_FANTASY_PAGEVIEWS),'DBNULL_TEXT') + ISNULL(RTRIM(CURR_SSN_M_FANTASY_PAGEVIEWS),'DBNULL_TEXT') + ISNULL(RTRIM(CURR_SSN_WEB_PAGEVIEWS),'DBNULL_TEXT') + ISNULL(RTRIM(CUST_ID),'DBNULL_TEXT') + ISNULL(RTRIM(CUST_RECENCY_DT),'DBNULL_TEXT') + ISNULL(RTRIM(DTV_COMMERICAL_ACTIVE_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(DTV_COMMERICAL_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(DTV_SUNDAY_TICKET_ACTIVE_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(DTV_SUNDAY_TICKET_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(DTV_TV_ACTIVE_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(DTV_TV_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(EM_LST_CLICK_DT),'DBNULL_TEXT') + ISNULL(RTRIM(EM_LST_DCOM_CLICK_DT),'DBNULL_TEXT') + ISNULL(RTRIM(EM_LST_DCOM_OPEN_DT),'DBNULL_TEXT') + ISNULL(RTRIM(EM_LST_MOBILE_CLICK_DT),'DBNULL_TEXT') + ISNULL(RTRIM(EM_LST_MOBILE_OPEN_DT),'DBNULL_TEXT') + ISNULL(RTRIM(EM_LST_OPEN_DT),'DBNULL_TEXT') + ISNULL(RTRIM(EM_LST_SMRTPH_CLICK_DT),'DBNULL_TEXT') + ISNULL(RTRIM(EM_LST_SMRTPH_OPEN_DT),'DBNULL_TEXT') + ISNULL(RTRIM(EM_LST_TABLT_CLICK_DT),'DBNULL_TEXT') + ISNULL(RTRIM(EM_LST_TABLT_OPEN_DT),'DBNULL_TEXT') + ISNULL(RTRIM(EMAIL_ADDR),'DBNULL_TEXT') + ISNULL(RTRIM(EMAIL_ID),'DBNULL_TEXT') + ISNULL(RTRIM(EMAILABLE_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(EPS_CRTD_DT),'DBNULL_TEXT') + ISNULL(RTRIM(FANTASY_LST_VST_DT),'DBNULL_TEXT') + ISNULL(RTRIM(FAV_TEAM_CD),'DBNULL_TEXT') + ISNULL(RTRIM(FIRST_NM),'DBNULL_TEXT') + ISNULL(RTRIM(GENDER),'DBNULL_TEXT') + ISNULL(RTRIM(GIGYA_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(IN_MARKET_CD),'DBNULL_TEXT') + ISNULL(RTRIM(INDIV_ID),'DBNULL_TEXT') + ISNULL(RTRIM(JETS_CROSSOVER_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(LAST_NM),'DBNULL_TEXT') + ISNULL(RTRIM(LST_CLUBS_STB_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_CLUBS_STH_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_DRAFT_FMP_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_FANT_CUSTOM_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_FANT_LM_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_FANT_MANAGED_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_FANT_UE_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_FANTASY_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_GPD_FT_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_GPD_SUB_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_GPI_FT_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_GPI_SUB_FYT_SSN_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(LST_GPI_SUB_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_GPI_SUB_SSN_SSN_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(LST_GPI_SUB_SSNPLS_SSN_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(LST_GPI_SUB_WKLY_SSN_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(LST_KICKOFF_FMP_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_M_FANTASY_VST_DT),'DBNULL_TEXT') + ISNULL(RTRIM(LST_MINIGM_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_MINIGM_SSN_REG_DT),'DBNULL_TEXT') + ISNULL(RTRIM(LST_NFL_NOW_SIGNUP_DT),'DBNULL_TEXT') + ISNULL(RTRIM(LST_PB_STB_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_PB_STH_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_PERFCH_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_PERFCH_SSN_REG_DT),'DBNULL_TEXT') + ISNULL(RTRIM(LST_PICKEM_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_PICKEM_SSN_REG_DT),'DBNULL_TEXT') + ISNULL(RTRIM(LST_PLAYCH_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_PLAYCH_SSN_REG_DT),'DBNULL_TEXT') + ISNULL(RTRIM(LST_PTP_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_PTP_SSN_REG_DT),'DBNULL_TEXT') + ISNULL(RTRIM(LST_SB_FMP_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_SUB_PROD),'DBNULL_TEXT') + ISNULL(RTRIM(LST_SUB_PROD_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(LST_TICKET_EXCH_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(MADDEN_PLAYER_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(MIDDLE_NM),'DBNULL_TEXT') + ISNULL(RTRIM(NFLN_SURVEY_AWARE_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(NFLN_SURVEY_HAVE_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(ORIG_EPS_FCM_CRTD_DT),'DBNULL_TEXT') + ISNULL(RTRIM(ORIG_SRC),'DBNULL_TEXT') + ISNULL(RTRIM(ORIG_SRC_BU),'DBNULL_TEXT') + ISNULL(RTRIM(ORIG_SRC_DT),'DBNULL_TEXT') + ISNULL(RTRIM(PREV_SSN_APP_VISITS),'DBNULL_TEXT') + ISNULL(RTRIM(PREV_SSN_FANTASY_PAGEVIEWS),'DBNULL_TEXT') + ISNULL(RTRIM(PREV_SSN_M_FANTASY_PAGEVIEWS),'DBNULL_TEXT') + ISNULL(RTRIM(PREV_SSN_WEB_PAGEVIEWS),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_BT_DOL),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_BT_PURCHASES),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_CANCER_DOL),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_CANCER_PURCHASES),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_DOL_1YR),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_DOL_3M),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_DOL_6M),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_DOL_TOTAL),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_HOMEOFF_DOL),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_HOMEOFF_PURCHASES),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_JERSEYS_DOL),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_JERSEYS_PURCHASES),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_LST_BT_PURCH_DT),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_LST_CANCER_PURCH_DT),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_LST_HOMEOFF_PURCH_DT),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_LST_JERSEYS_PURCH_DT),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_LST_MENS_PURCH_DT),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_LST_PLUS_PURCH_DT),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_LST_PURCH_DT),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_LST_UNDERMINED_PURCH_DT),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_LST_WOMENS_PURCH_DT),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_LST_YOUTH_PURCH_DT),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_MENS_DOL),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_MENS_PURCHASES),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_ORD_TOTAL),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_PLUS_DOL),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_PLUS_PURCHASES),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_UNDERMINED_DOL),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_UNDERMINED_PURCHASES),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_WOMENS_DOL),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_WOMENS_PURCHASES),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_YOUTH_DOL),'DBNULL_TEXT') + ISNULL(RTRIM(SHOP_YOUTH_PURCHASES),'DBNULL_TEXT') + ISNULL(RTRIM(SOCIAL_FACEBOOK_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(SOCIAL_GOOGLEPLUS_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(SOCIAL_MESSENGER_FLG),'DBNULL_TEXT') + ISNULL(RTRIM(TEAM_LONG_NM),'DBNULL_TEXT') + ISNULL(RTRIM(TICKET_EXCH_LST_DT),'DBNULL_TEXT') + ISNULL(RTRIM(TICKET_EXCH_NUMSEATS),'DBNULL_TEXT') + ISNULL(RTRIM(TICKET_EXCH_ORDERS),'DBNULL_TEXT') + ISNULL(RTRIM(TICKET_EXCH_REV),'DBNULL_TEXT') + ISNULL(RTRIM(TOTAL_CURR_SSN_APP_VISITS),'DBNULL_TEXT') + ISNULL(RTRIM(TOTAL_CURR_SSN_FANTASY_PAGEVW),'DBNULL_TEXT') + ISNULL(RTRIM(TOTAL_CURR_SSN_M_FANT_PAGEVW),'DBNULL_TEXT') + ISNULL(RTRIM(TOTAL_SSN_WEB_PAGEVIEWS),'DBNULL_TEXT') + ISNULL(RTRIM(TRANSACTIONAL_VALUE),'DBNULL_TEXT') + ISNULL(RTRIM(TRANSACTIONAL_VALUE_CURR_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(TRANSACTIONAL_VALUE_PREV_SSN),'DBNULL_TEXT') + ISNULL(RTRIM(USERNAME),'DBNULL_TEXT') + ISNULL(RTRIM(WEB_LST_VST_DT),'DBNULL_TEXT'))


EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Src Table Setup', 'ETL_DeltaHashKey Set', @ExecutionId


CREATE NONCLUSTERED INDEX IDX_Load_Key ON #SrcData (CUST_ID)
CREATE NONCLUSTERED INDEX IDX_ETL_DeltaHashKey ON #SrcData (ETL_DeltaHashKey)


DELETE A
from #SrcData A
join ods.FanCentric_Customers B
on A.CUST_ID = B.CUST_ID
and B.ETL_IsDeleted = 0
and A.ETL_DeltaHashKey = B.ETL_DeltaHashKey;


EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Src Table Setup', 'Temp Table Indexes Created', @ExecutionId
EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Merge Statement Execution', 'Start', @ExecutionId


/*****

2017-09-27 by DCH:	The merge was performing poorly, so I broke apart the statement into three parts.

*****/
--	update changed records
UPDATE myTarget
SET	   myTarget.[ETL_UpdatedDate] = @RunTime
     , myTarget.[ETL_IsDeleted] = 0
     , myTarget.[ETL_DeletedDate] = NULL
     , myTarget.[ETL_DeltaHashKey] = mySource.[ETL_DeltaHashKey]
     , myTarget.[CUST_ID] = mySource.[CUST_ID]
     , myTarget.[EMAIL_ID] = mySource.[EMAIL_ID]
     , myTarget.[EMAIL_ADDR] = mySource.[EMAIL_ADDR]
     , myTarget.[EMAILABLE_FLG] = mySource.[EMAILABLE_FLG]
     , myTarget.[USERNAME] = mySource.[USERNAME]
     , myTarget.[ADDR_ID] = mySource.[ADDR_ID]
     , myTarget.[INDIV_ID] = mySource.[INDIV_ID]
     , myTarget.[FAV_TEAM_CD] = mySource.[FAV_TEAM_CD]
     , myTarget.[TEAM_LONG_NM] = mySource.[TEAM_LONG_NM]
     , myTarget.[GENDER] = mySource.[GENDER]
     , myTarget.[FIRST_NM] = mySource.[FIRST_NM]
     , myTarget.[LAST_NM] = mySource.[LAST_NM]
     , myTarget.[MIDDLE_NM] = mySource.[MIDDLE_NM]
     , myTarget.[ACE_PRIM_ADDR] = mySource.[ACE_PRIM_ADDR]
     , myTarget.[ACE_SEC_ADDR] = mySource.[ACE_SEC_ADDR]
     , myTarget.[ACE_CITY] = mySource.[ACE_CITY]
     , myTarget.[ACE_STATE] = mySource.[ACE_STATE]
     , myTarget.[ACE_POSTAL_CODE] = mySource.[ACE_POSTAL_CODE]
     , myTarget.[ACE_ISO_CODE] = mySource.[ACE_ISO_CODE]
     , myTarget.[BIRTH_DT] = mySource.[BIRTH_DT]
     , myTarget.[AGE] = mySource.[AGE]
     , myTarget.[ORIG_SRC] = mySource.[ORIG_SRC]
     , myTarget.[ORIG_SRC_DT] = mySource.[ORIG_SRC_DT]
     , myTarget.[ORIG_SRC_BU] = mySource.[ORIG_SRC_BU]
     , myTarget.[ORIG_EPS_FCM_CRTD_DT] = mySource.[ORIG_EPS_FCM_CRTD_DT]
     , myTarget.[IN_MARKET_CD] = mySource.[IN_MARKET_CD]
     , myTarget.[BU_CLUBS_FLG] = mySource.[BU_CLUBS_FLG]
     , myTarget.[BU_DCOM_FLG] = mySource.[BU_DCOM_FLG]
     , myTarget.[BU_LIVE_EVENT_FLG] = mySource.[BU_LIVE_EVENT_FLG]
     , myTarget.[BU_PRTR_FLG] = mySource.[BU_PRTR_FLG]
     , myTarget.[BU_SHOP_FLG] = mySource.[BU_SHOP_FLG]
     , myTarget.[BU_YUTH_FLG] = mySource.[BU_YUTH_FLG]
     , myTarget.[BU_INTL_FLG] = mySource.[BU_INTL_FLG]
     , myTarget.[BU_OTHR_FLG] = mySource.[BU_OTHR_FLG]
     , myTarget.[BU_MKTG_FLG] = mySource.[BU_MKTG_FLG]
     , myTarget.[JETS_CROSSOVER_FLG] = mySource.[JETS_CROSSOVER_FLG]
     , myTarget.[CROSSOVER_BU_CD] = mySource.[CROSSOVER_BU_CD]
     , myTarget.[CROSSOVER_PRODUCT_CD] = mySource.[CROSSOVER_PRODUCT_CD]
     , myTarget.[LST_FANTASY_SSN] = mySource.[LST_FANTASY_SSN]
     , myTarget.[LST_FANT_LM_SSN] = mySource.[LST_FANT_LM_SSN]
     , myTarget.[LST_FANT_UE_SSN] = mySource.[LST_FANT_UE_SSN]
     , myTarget.[LST_FANT_CUSTOM_SSN] = mySource.[LST_FANT_CUSTOM_SSN]
     , myTarget.[LST_FANT_MANAGED_SSN] = mySource.[LST_FANT_MANAGED_SSN]
     , myTarget.[LST_SUB_PROD] = mySource.[LST_SUB_PROD]
     , myTarget.[LST_SUB_PROD_SSN] = mySource.[LST_SUB_PROD_SSN]
     , myTarget.[LST_GPD_SUB_SSN] = mySource.[LST_GPD_SUB_SSN]
     , myTarget.[LST_GPD_FT_SSN] = mySource.[LST_GPD_FT_SSN]
     , myTarget.[LST_GPI_SUB_SSN] = mySource.[LST_GPI_SUB_SSN]
     , myTarget.[LST_GPI_FT_SSN] = mySource.[LST_GPI_FT_SSN]
     , myTarget.[LST_GPI_SUB_SSN_SSN_FLG] = mySource.[LST_GPI_SUB_SSN_SSN_FLG]
     , myTarget.[LST_GPI_SUB_SSNPLS_SSN_FLG] = mySource.[LST_GPI_SUB_SSNPLS_SSN_FLG]
     , myTarget.[LST_GPI_SUB_WKLY_SSN_FLG] = mySource.[LST_GPI_SUB_WKLY_SSN_FLG]
     , myTarget.[LST_GPI_SUB_FYT_SSN_FLG] = mySource.[LST_GPI_SUB_FYT_SSN_FLG]
     , myTarget.[LST_NFL_NOW_SIGNUP_DT] = mySource.[LST_NFL_NOW_SIGNUP_DT]
     , myTarget.[LST_MINIGM_SSN] = mySource.[LST_MINIGM_SSN]
     , myTarget.[LST_MINIGM_SSN_REG_DT] = mySource.[LST_MINIGM_SSN_REG_DT]
     , myTarget.[LST_PERFCH_SSN] = mySource.[LST_PERFCH_SSN]
     , myTarget.[LST_PERFCH_SSN_REG_DT] = mySource.[LST_PERFCH_SSN_REG_DT]
     , myTarget.[LST_PLAYCH_SSN] = mySource.[LST_PLAYCH_SSN]
     , myTarget.[LST_PLAYCH_SSN_REG_DT] = mySource.[LST_PLAYCH_SSN_REG_DT]
     , myTarget.[LST_PICKEM_SSN] = mySource.[LST_PICKEM_SSN]
     , myTarget.[LST_PICKEM_SSN_REG_DT] = mySource.[LST_PICKEM_SSN_REG_DT]
     , myTarget.[LST_PTP_SSN] = mySource.[LST_PTP_SSN]
     , myTarget.[LST_PTP_SSN_REG_DT] = mySource.[LST_PTP_SSN_REG_DT]
     , myTarget.[LST_DRAFT_FMP_SSN] = mySource.[LST_DRAFT_FMP_SSN]
     , myTarget.[LST_KICKOFF_FMP_SSN] = mySource.[LST_KICKOFF_FMP_SSN]
     , myTarget.[LST_SB_FMP_SSN] = mySource.[LST_SB_FMP_SSN]
     , myTarget.[LST_PB_STH_SSN] = mySource.[LST_PB_STH_SSN]
     , myTarget.[LST_PB_STB_SSN] = mySource.[LST_PB_STB_SSN]
     , myTarget.[SHOP_LST_PURCH_DT] = mySource.[SHOP_LST_PURCH_DT]
     , myTarget.[SHOP_DOL_3M] = mySource.[SHOP_DOL_3M]
     , myTarget.[SHOP_DOL_6M] = mySource.[SHOP_DOL_6M]
     , myTarget.[SHOP_DOL_1YR] = mySource.[SHOP_DOL_1YR]
     , myTarget.[SHOP_DOL_TOTAL] = mySource.[SHOP_DOL_TOTAL]
     , myTarget.[SHOP_ORD_TOTAL] = mySource.[SHOP_ORD_TOTAL]
     , myTarget.[SHOP_LST_CANCER_PURCH_DT] = mySource.[SHOP_LST_CANCER_PURCH_DT]
     , myTarget.[SHOP_CANCER_PURCHASES] = mySource.[SHOP_CANCER_PURCHASES]
     , myTarget.[SHOP_CANCER_DOL] = mySource.[SHOP_CANCER_DOL]
     , myTarget.[SHOP_LST_BT_PURCH_DT] = mySource.[SHOP_LST_BT_PURCH_DT]
     , myTarget.[SHOP_BT_PURCHASES] = mySource.[SHOP_BT_PURCHASES]
     , myTarget.[SHOP_BT_DOL] = mySource.[SHOP_BT_DOL]
     , myTarget.[SHOP_LST_JERSEYS_PURCH_DT] = mySource.[SHOP_LST_JERSEYS_PURCH_DT]
     , myTarget.[SHOP_JERSEYS_PURCHASES] = mySource.[SHOP_JERSEYS_PURCHASES]
     , myTarget.[SHOP_JERSEYS_DOL] = mySource.[SHOP_JERSEYS_DOL]
     , myTarget.[SHOP_LST_HOMEOFF_PURCH_DT] = mySource.[SHOP_LST_HOMEOFF_PURCH_DT]
     , myTarget.[SHOP_HOMEOFF_PURCHASES] = mySource.[SHOP_HOMEOFF_PURCHASES]
     , myTarget.[SHOP_HOMEOFF_DOL] = mySource.[SHOP_HOMEOFF_DOL]
     , myTarget.[SHOP_LST_MENS_PURCH_DT] = mySource.[SHOP_LST_MENS_PURCH_DT]
     , myTarget.[SHOP_MENS_PURCHASES] = mySource.[SHOP_MENS_PURCHASES]
     , myTarget.[SHOP_MENS_DOL] = mySource.[SHOP_MENS_DOL]
     , myTarget.[SHOP_LST_PLUS_PURCH_DT] = mySource.[SHOP_LST_PLUS_PURCH_DT]
     , myTarget.[SHOP_PLUS_PURCHASES] = mySource.[SHOP_PLUS_PURCHASES]
     , myTarget.[SHOP_PLUS_DOL] = mySource.[SHOP_PLUS_DOL]
     , myTarget.[SHOP_LST_YOUTH_PURCH_DT] = mySource.[SHOP_LST_YOUTH_PURCH_DT]
     , myTarget.[SHOP_YOUTH_PURCHASES] = mySource.[SHOP_YOUTH_PURCHASES]
     , myTarget.[SHOP_YOUTH_DOL] = mySource.[SHOP_YOUTH_DOL]
     , myTarget.[SHOP_LST_WOMENS_PURCH_DT] = mySource.[SHOP_LST_WOMENS_PURCH_DT]
     , myTarget.[SHOP_WOMENS_PURCHASES] = mySource.[SHOP_WOMENS_PURCHASES]
     , myTarget.[SHOP_WOMENS_DOL] = mySource.[SHOP_WOMENS_DOL]
     , myTarget.[SHOP_LST_UNDERMINED_PURCH_DT] = mySource.[SHOP_LST_UNDERMINED_PURCH_DT]
     , myTarget.[SHOP_UNDERMINED_PURCHASES] = mySource.[SHOP_UNDERMINED_PURCHASES]
     , myTarget.[SHOP_UNDERMINED_DOL] = mySource.[SHOP_UNDERMINED_DOL]
     , myTarget.[ACTIVE_0_3M_FLAG] = mySource.[ACTIVE_0_3M_FLAG]
     , myTarget.[ACTIVE_4_6M_FLAG] = mySource.[ACTIVE_4_6M_FLAG]
     , myTarget.[ACTIVE_7_12M_FLAG] = mySource.[ACTIVE_7_12M_FLAG]
     , myTarget.[ACTIVE_1YR_FLAG] = mySource.[ACTIVE_1YR_FLAG]
     , myTarget.[ACTIVE_2YR_FLAG] = mySource.[ACTIVE_2YR_FLAG]
     , myTarget.[ACTIVE_3YR_FLAG] = mySource.[ACTIVE_3YR_FLAG]
     , myTarget.[CUST_RECENCY_DT] = mySource.[CUST_RECENCY_DT]
     , myTarget.[EM_LST_OPEN_DT] = mySource.[EM_LST_OPEN_DT]
     , myTarget.[EM_LST_DCOM_OPEN_DT] = mySource.[EM_LST_DCOM_OPEN_DT]
     , myTarget.[EM_LST_MOBILE_OPEN_DT] = mySource.[EM_LST_MOBILE_OPEN_DT]
     , myTarget.[EM_LST_SMRTPH_OPEN_DT] = mySource.[EM_LST_SMRTPH_OPEN_DT]
     , myTarget.[EM_LST_TABLT_OPEN_DT] = mySource.[EM_LST_TABLT_OPEN_DT]
     , myTarget.[EM_LST_CLICK_DT] = mySource.[EM_LST_CLICK_DT]
     , myTarget.[EM_LST_DCOM_CLICK_DT] = mySource.[EM_LST_DCOM_CLICK_DT]
     , myTarget.[EM_LST_MOBILE_CLICK_DT] = mySource.[EM_LST_MOBILE_CLICK_DT]
     , myTarget.[EM_LST_SMRTPH_CLICK_DT] = mySource.[EM_LST_SMRTPH_CLICK_DT]
     , myTarget.[EM_LST_TABLT_CLICK_DT] = mySource.[EM_LST_TABLT_CLICK_DT]
     , myTarget.[WEB_LST_VST_DT] = mySource.[WEB_LST_VST_DT]
     , myTarget.[APP_LST_VST_DT] = mySource.[APP_LST_VST_DT]
     , myTarget.[FANTASY_LST_VST_DT] = mySource.[FANTASY_LST_VST_DT]
     , myTarget.[LST_M_FANTASY_VST_DT] = mySource.[LST_M_FANTASY_VST_DT]
     , myTarget.[CURR_SSN_WEB_PAGEVIEWS] = mySource.[CURR_SSN_WEB_PAGEVIEWS]
     , myTarget.[CURR_SSN_FANTASY_PAGEVIEWS] = mySource.[CURR_SSN_FANTASY_PAGEVIEWS]
     , myTarget.[CURR_SSN_APP_VISITS] = mySource.[CURR_SSN_APP_VISITS]
     , myTarget.[CURR_SSN_M_FANTASY_PAGEVIEWS] = mySource.[CURR_SSN_M_FANTASY_PAGEVIEWS]
     , myTarget.[PREV_SSN_WEB_PAGEVIEWS] = mySource.[PREV_SSN_WEB_PAGEVIEWS]
     , myTarget.[PREV_SSN_FANTASY_PAGEVIEWS] = mySource.[PREV_SSN_FANTASY_PAGEVIEWS]
     , myTarget.[PREV_SSN_APP_VISITS] = mySource.[PREV_SSN_APP_VISITS]
     , myTarget.[PREV_SSN_M_FANTASY_PAGEVIEWS] = mySource.[PREV_SSN_M_FANTASY_PAGEVIEWS]
     , myTarget.[TOTAL_SSN_WEB_PAGEVIEWS] = mySource.[TOTAL_SSN_WEB_PAGEVIEWS]
     , myTarget.[TOTAL_CURR_SSN_FANTASY_PAGEVW] = mySource.[TOTAL_CURR_SSN_FANTASY_PAGEVW]
     , myTarget.[TOTAL_CURR_SSN_APP_VISITS] = mySource.[TOTAL_CURR_SSN_APP_VISITS]
     , myTarget.[TOTAL_CURR_SSN_M_FANT_PAGEVW] = mySource.[TOTAL_CURR_SSN_M_FANT_PAGEVW]
     , myTarget.[LST_CLUBS_STH_SSN] = mySource.[LST_CLUBS_STH_SSN]
     , myTarget.[LST_CLUBS_STB_SSN] = mySource.[LST_CLUBS_STB_SSN]
     , myTarget.[CLUBS_STB_TIX_REV] = mySource.[CLUBS_STB_TIX_REV]
     , myTarget.[CLUBS_STB_TIX_ORDERS] = mySource.[CLUBS_STB_TIX_ORDERS]
     , myTarget.[CLUBS_STB_TIX_LST_DT] = mySource.[CLUBS_STB_TIX_LST_DT]
     , myTarget.[CLUBS_STB_NUMSEATS] = mySource.[CLUBS_STB_NUMSEATS]
     , myTarget.[LST_TICKET_EXCH_SSN] = mySource.[LST_TICKET_EXCH_SSN]
     , myTarget.[TICKET_EXCH_REV] = mySource.[TICKET_EXCH_REV]
     , myTarget.[TICKET_EXCH_ORDERS] = mySource.[TICKET_EXCH_ORDERS]
     , myTarget.[TICKET_EXCH_LST_DT] = mySource.[TICKET_EXCH_LST_DT]
     , myTarget.[TICKET_EXCH_NUMSEATS] = mySource.[TICKET_EXCH_NUMSEATS]
     , myTarget.[DTV_SUNDAY_TICKET_FLG] = mySource.[DTV_SUNDAY_TICKET_FLG]
     , myTarget.[DTV_SUNDAY_TICKET_ACTIVE_FLG] = mySource.[DTV_SUNDAY_TICKET_ACTIVE_FLG]
     , myTarget.[DTV_TV_FLG] = mySource.[DTV_TV_FLG]
     , myTarget.[DTV_TV_ACTIVE_FLG] = mySource.[DTV_TV_ACTIVE_FLG]
     , myTarget.[DTV_COMMERICAL_FLG] = mySource.[DTV_COMMERICAL_FLG]
     , myTarget.[DTV_COMMERICAL_ACTIVE_FLG] = mySource.[DTV_COMMERICAL_ACTIVE_FLG]
     , myTarget.[MADDEN_PLAYER_FLG] = mySource.[MADDEN_PLAYER_FLG]
     , myTarget.[NFLN_SURVEY_HAVE_FLG] = mySource.[NFLN_SURVEY_HAVE_FLG]
     , myTarget.[NFLN_SURVEY_AWARE_FLG] = mySource.[NFLN_SURVEY_AWARE_FLG]
     , myTarget.[GIGYA_FLG] = mySource.[GIGYA_FLG]
     , myTarget.[SOCIAL_FACEBOOK_FLG] = mySource.[SOCIAL_FACEBOOK_FLG]
     , myTarget.[SOCIAL_GOOGLEPLUS_FLG] = mySource.[SOCIAL_GOOGLEPLUS_FLG]
     , myTarget.[SOCIAL_MESSENGER_FLG] = mySource.[SOCIAL_MESSENGER_FLG]
     , myTarget.[TRANSACTIONAL_VALUE] = mySource.[TRANSACTIONAL_VALUE]
     , myTarget.[TRANSACTIONAL_VALUE_CURR_SSN] = mySource.[TRANSACTIONAL_VALUE_CURR_SSN]
     , myTarget.[TRANSACTIONAL_VALUE_PREV_SSN] = mySource.[TRANSACTIONAL_VALUE_PREV_SSN]
     , myTarget.[EPS_CRTD_DT] = mySource.[EPS_CRTD_DT]
FROM ods.FanCentric_Customers AS myTarget
JOIN #SrcData AS mySource
ON myTarget.CUST_ID = mySource.CUST_ID
WHERE (
	ISNULL(mySource.ETL_DeltaHashKey,-1) <> ISNULL(myTarget.ETL_DeltaHashKey, -1)
	OR myTarget.ETL_IsDeleted = 1
);



--	soft-delete records not in source
UPDATE myTarget
SET	   myTarget.[ETL_IsDeleted] = 1
	 , myTarget.[ETL_DeletedDate] = @RunTime
FROM ods.FanCentric_Customers AS myTarget
LEFT JOIN #SrcData AS mySource
ON myTarget.CUST_ID = mySource.CUST_ID
WHERE mySource.CUST_ID IS NULL;



--	insert records not in target
INSERT ods.FanCentric_Customers
     ([ETL_CreatedDate]
     ,[ETL_UpdatedDate]
     ,[ETL_IsDeleted]
     ,[ETL_DeletedDate]
     ,[ETL_DeltaHashKey]
     ,[ETL_FileName]
     ,[CUST_ID]
     ,[EMAIL_ID]
     ,[EMAIL_ADDR]
     ,[EMAILABLE_FLG]
     ,[USERNAME]
     ,[ADDR_ID]
     ,[INDIV_ID]
     ,[FAV_TEAM_CD]
     ,[TEAM_LONG_NM]
     ,[GENDER]
     ,[FIRST_NM]
     ,[LAST_NM]
     ,[MIDDLE_NM]
     ,[ACE_PRIM_ADDR]
     ,[ACE_SEC_ADDR]
     ,[ACE_CITY]
     ,[ACE_STATE]
     ,[ACE_POSTAL_CODE]
     ,[ACE_ISO_CODE]
     ,[BIRTH_DT]
     ,[AGE]
     ,[ORIG_SRC]
     ,[ORIG_SRC_DT]
     ,[ORIG_SRC_BU]
     ,[ORIG_EPS_FCM_CRTD_DT]
     ,[IN_MARKET_CD]
     ,[BU_CLUBS_FLG]
     ,[BU_DCOM_FLG]
     ,[BU_LIVE_EVENT_FLG]
     ,[BU_PRTR_FLG]
     ,[BU_SHOP_FLG]
     ,[BU_YUTH_FLG]
     ,[BU_INTL_FLG]
     ,[BU_OTHR_FLG]
     ,[BU_MKTG_FLG]
     ,[JETS_CROSSOVER_FLG]
     ,[CROSSOVER_BU_CD]
     ,[CROSSOVER_PRODUCT_CD]
     ,[LST_FANTASY_SSN]
     ,[LST_FANT_LM_SSN]
     ,[LST_FANT_UE_SSN]
     ,[LST_FANT_CUSTOM_SSN]
     ,[LST_FANT_MANAGED_SSN]
     ,[LST_SUB_PROD]
     ,[LST_SUB_PROD_SSN]
     ,[LST_GPD_SUB_SSN]
     ,[LST_GPD_FT_SSN]
     ,[LST_GPI_SUB_SSN]
     ,[LST_GPI_FT_SSN]
     ,[LST_GPI_SUB_SSN_SSN_FLG]
     ,[LST_GPI_SUB_SSNPLS_SSN_FLG]
     ,[LST_GPI_SUB_WKLY_SSN_FLG]
     ,[LST_GPI_SUB_FYT_SSN_FLG]
     ,[LST_NFL_NOW_SIGNUP_DT]
     ,[LST_MINIGM_SSN]
     ,[LST_MINIGM_SSN_REG_DT]
     ,[LST_PERFCH_SSN]
     ,[LST_PERFCH_SSN_REG_DT]
     ,[LST_PLAYCH_SSN]
     ,[LST_PLAYCH_SSN_REG_DT]
     ,[LST_PICKEM_SSN]
     ,[LST_PICKEM_SSN_REG_DT]
     ,[LST_PTP_SSN]
     ,[LST_PTP_SSN_REG_DT]
     ,[LST_DRAFT_FMP_SSN]
     ,[LST_KICKOFF_FMP_SSN]
     ,[LST_SB_FMP_SSN]
     ,[LST_PB_STH_SSN]
     ,[LST_PB_STB_SSN]
     ,[SHOP_LST_PURCH_DT]
     ,[SHOP_DOL_3M]
     ,[SHOP_DOL_6M]
     ,[SHOP_DOL_1YR]
     ,[SHOP_DOL_TOTAL]
     ,[SHOP_ORD_TOTAL]
     ,[SHOP_LST_CANCER_PURCH_DT]
     ,[SHOP_CANCER_PURCHASES]
     ,[SHOP_CANCER_DOL]
     ,[SHOP_LST_BT_PURCH_DT]
     ,[SHOP_BT_PURCHASES]
     ,[SHOP_BT_DOL]
     ,[SHOP_LST_JERSEYS_PURCH_DT]
     ,[SHOP_JERSEYS_PURCHASES]
     ,[SHOP_JERSEYS_DOL]
     ,[SHOP_LST_HOMEOFF_PURCH_DT]
     ,[SHOP_HOMEOFF_PURCHASES]
     ,[SHOP_HOMEOFF_DOL]
     ,[SHOP_LST_MENS_PURCH_DT]
     ,[SHOP_MENS_PURCHASES]
     ,[SHOP_MENS_DOL]
     ,[SHOP_LST_PLUS_PURCH_DT]
     ,[SHOP_PLUS_PURCHASES]
     ,[SHOP_PLUS_DOL]
     ,[SHOP_LST_YOUTH_PURCH_DT]
     ,[SHOP_YOUTH_PURCHASES]
     ,[SHOP_YOUTH_DOL]
     ,[SHOP_LST_WOMENS_PURCH_DT]
     ,[SHOP_WOMENS_PURCHASES]
     ,[SHOP_WOMENS_DOL]
     ,[SHOP_LST_UNDERMINED_PURCH_DT]
     ,[SHOP_UNDERMINED_PURCHASES]
     ,[SHOP_UNDERMINED_DOL]
     ,[ACTIVE_0_3M_FLAG]
     ,[ACTIVE_4_6M_FLAG]
     ,[ACTIVE_7_12M_FLAG]
     ,[ACTIVE_1YR_FLAG]
     ,[ACTIVE_2YR_FLAG]
     ,[ACTIVE_3YR_FLAG]
     ,[CUST_RECENCY_DT]
     ,[EM_LST_OPEN_DT]
     ,[EM_LST_DCOM_OPEN_DT]
     ,[EM_LST_MOBILE_OPEN_DT]
     ,[EM_LST_SMRTPH_OPEN_DT]
     ,[EM_LST_TABLT_OPEN_DT]
     ,[EM_LST_CLICK_DT]
     ,[EM_LST_DCOM_CLICK_DT]
     ,[EM_LST_MOBILE_CLICK_DT]
     ,[EM_LST_SMRTPH_CLICK_DT]
     ,[EM_LST_TABLT_CLICK_DT]
     ,[WEB_LST_VST_DT]
     ,[APP_LST_VST_DT]
     ,[FANTASY_LST_VST_DT]
     ,[LST_M_FANTASY_VST_DT]
     ,[CURR_SSN_WEB_PAGEVIEWS]
     ,[CURR_SSN_FANTASY_PAGEVIEWS]
     ,[CURR_SSN_APP_VISITS]
     ,[CURR_SSN_M_FANTASY_PAGEVIEWS]
     ,[PREV_SSN_WEB_PAGEVIEWS]
     ,[PREV_SSN_FANTASY_PAGEVIEWS]
     ,[PREV_SSN_APP_VISITS]
     ,[PREV_SSN_M_FANTASY_PAGEVIEWS]
     ,[TOTAL_SSN_WEB_PAGEVIEWS]
     ,[TOTAL_CURR_SSN_FANTASY_PAGEVW]
     ,[TOTAL_CURR_SSN_APP_VISITS]
     ,[TOTAL_CURR_SSN_M_FANT_PAGEVW]
     ,[LST_CLUBS_STH_SSN]
     ,[LST_CLUBS_STB_SSN]
     ,[CLUBS_STB_TIX_REV]
     ,[CLUBS_STB_TIX_ORDERS]
     ,[CLUBS_STB_TIX_LST_DT]
     ,[CLUBS_STB_NUMSEATS]
     ,[LST_TICKET_EXCH_SSN]
     ,[TICKET_EXCH_REV]
     ,[TICKET_EXCH_ORDERS]
     ,[TICKET_EXCH_LST_DT]
     ,[TICKET_EXCH_NUMSEATS]
     ,[DTV_SUNDAY_TICKET_FLG]
     ,[DTV_SUNDAY_TICKET_ACTIVE_FLG]
     ,[DTV_TV_FLG]
     ,[DTV_TV_ACTIVE_FLG]
     ,[DTV_COMMERICAL_FLG]
     ,[DTV_COMMERICAL_ACTIVE_FLG]
     ,[MADDEN_PLAYER_FLG]
     ,[NFLN_SURVEY_HAVE_FLG]
     ,[NFLN_SURVEY_AWARE_FLG]
     ,[GIGYA_FLG]
     ,[SOCIAL_FACEBOOK_FLG]
     ,[SOCIAL_GOOGLEPLUS_FLG]
     ,[SOCIAL_MESSENGER_FLG]
     ,[TRANSACTIONAL_VALUE]
     ,[TRANSACTIONAL_VALUE_CURR_SSN]
     ,[TRANSACTIONAL_VALUE_PREV_SSN]
     ,[EPS_CRTD_DT]
     )
SELECT @RunTime	--ETL_CreatedDate
     ,@RunTime	--ETL_UpdateddDate
     ,0			--ETL_IsDeleted
     ,NULL		--ETL_DeletedDate
     ,mySource.[ETL_DeltaHashKey]
	 ,mySource.[ETL_FileName]
     ,mySource.[CUST_ID]
     ,mySource.[EMAIL_ID]
     ,mySource.[EMAIL_ADDR]
     ,mySource.[EMAILABLE_FLG]
     ,mySource.[USERNAME]
     ,mySource.[ADDR_ID]
     ,mySource.[INDIV_ID]
     ,mySource.[FAV_TEAM_CD]
     ,mySource.[TEAM_LONG_NM]
     ,mySource.[GENDER]
     ,mySource.[FIRST_NM]
     ,mySource.[LAST_NM]
     ,mySource.[MIDDLE_NM]
     ,mySource.[ACE_PRIM_ADDR]
     ,mySource.[ACE_SEC_ADDR]
     ,mySource.[ACE_CITY]
     ,mySource.[ACE_STATE]
     ,mySource.[ACE_POSTAL_CODE]
     ,mySource.[ACE_ISO_CODE]
     ,mySource.[BIRTH_DT]
     ,mySource.[AGE]
     ,mySource.[ORIG_SRC]
     ,mySource.[ORIG_SRC_DT]
     ,mySource.[ORIG_SRC_BU]
     ,mySource.[ORIG_EPS_FCM_CRTD_DT]
     ,mySource.[IN_MARKET_CD]
     ,mySource.[BU_CLUBS_FLG]
     ,mySource.[BU_DCOM_FLG]
     ,mySource.[BU_LIVE_EVENT_FLG]
     ,mySource.[BU_PRTR_FLG]
     ,mySource.[BU_SHOP_FLG]
     ,mySource.[BU_YUTH_FLG]
     ,mySource.[BU_INTL_FLG]
     ,mySource.[BU_OTHR_FLG]
     ,mySource.[BU_MKTG_FLG]
     ,mySource.[JETS_CROSSOVER_FLG]
     ,mySource.[CROSSOVER_BU_CD]
     ,mySource.[CROSSOVER_PRODUCT_CD]
     ,mySource.[LST_FANTASY_SSN]
     ,mySource.[LST_FANT_LM_SSN]
     ,mySource.[LST_FANT_UE_SSN]
     ,mySource.[LST_FANT_CUSTOM_SSN]
     ,mySource.[LST_FANT_MANAGED_SSN]
     ,mySource.[LST_SUB_PROD]
     ,mySource.[LST_SUB_PROD_SSN]
     ,mySource.[LST_GPD_SUB_SSN]
     ,mySource.[LST_GPD_FT_SSN]
     ,mySource.[LST_GPI_SUB_SSN]
     ,mySource.[LST_GPI_FT_SSN]
     ,mySource.[LST_GPI_SUB_SSN_SSN_FLG]
     ,mySource.[LST_GPI_SUB_SSNPLS_SSN_FLG]
     ,mySource.[LST_GPI_SUB_WKLY_SSN_FLG]
     ,mySource.[LST_GPI_SUB_FYT_SSN_FLG]
     ,mySource.[LST_NFL_NOW_SIGNUP_DT]
     ,mySource.[LST_MINIGM_SSN]
     ,mySource.[LST_MINIGM_SSN_REG_DT]
     ,mySource.[LST_PERFCH_SSN]
     ,mySource.[LST_PERFCH_SSN_REG_DT]
     ,mySource.[LST_PLAYCH_SSN]
     ,mySource.[LST_PLAYCH_SSN_REG_DT]
     ,mySource.[LST_PICKEM_SSN]
     ,mySource.[LST_PICKEM_SSN_REG_DT]
     ,mySource.[LST_PTP_SSN]
     ,mySource.[LST_PTP_SSN_REG_DT]
     ,mySource.[LST_DRAFT_FMP_SSN]
     ,mySource.[LST_KICKOFF_FMP_SSN]
     ,mySource.[LST_SB_FMP_SSN]
     ,mySource.[LST_PB_STH_SSN]
     ,mySource.[LST_PB_STB_SSN]
     ,mySource.[SHOP_LST_PURCH_DT]
     ,mySource.[SHOP_DOL_3M]
     ,mySource.[SHOP_DOL_6M]
     ,mySource.[SHOP_DOL_1YR]
     ,mySource.[SHOP_DOL_TOTAL]
     ,mySource.[SHOP_ORD_TOTAL]
     ,mySource.[SHOP_LST_CANCER_PURCH_DT]
     ,mySource.[SHOP_CANCER_PURCHASES]
     ,mySource.[SHOP_CANCER_DOL]
     ,mySource.[SHOP_LST_BT_PURCH_DT]
     ,mySource.[SHOP_BT_PURCHASES]
     ,mySource.[SHOP_BT_DOL]
     ,mySource.[SHOP_LST_JERSEYS_PURCH_DT]
     ,mySource.[SHOP_JERSEYS_PURCHASES]
     ,mySource.[SHOP_JERSEYS_DOL]
     ,mySource.[SHOP_LST_HOMEOFF_PURCH_DT]
     ,mySource.[SHOP_HOMEOFF_PURCHASES]
     ,mySource.[SHOP_HOMEOFF_DOL]
     ,mySource.[SHOP_LST_MENS_PURCH_DT]
     ,mySource.[SHOP_MENS_PURCHASES]
     ,mySource.[SHOP_MENS_DOL]
     ,mySource.[SHOP_LST_PLUS_PURCH_DT]
     ,mySource.[SHOP_PLUS_PURCHASES]
     ,mySource.[SHOP_PLUS_DOL]
     ,mySource.[SHOP_LST_YOUTH_PURCH_DT]
     ,mySource.[SHOP_YOUTH_PURCHASES]
     ,mySource.[SHOP_YOUTH_DOL]
     ,mySource.[SHOP_LST_WOMENS_PURCH_DT]
     ,mySource.[SHOP_WOMENS_PURCHASES]
     ,mySource.[SHOP_WOMENS_DOL]
     ,mySource.[SHOP_LST_UNDERMINED_PURCH_DT]
     ,mySource.[SHOP_UNDERMINED_PURCHASES]
     ,mySource.[SHOP_UNDERMINED_DOL]
     ,mySource.[ACTIVE_0_3M_FLAG]
     ,mySource.[ACTIVE_4_6M_FLAG]
     ,mySource.[ACTIVE_7_12M_FLAG]
     ,mySource.[ACTIVE_1YR_FLAG]
     ,mySource.[ACTIVE_2YR_FLAG]
     ,mySource.[ACTIVE_3YR_FLAG]
     ,mySource.[CUST_RECENCY_DT]
     ,mySource.[EM_LST_OPEN_DT]
     ,mySource.[EM_LST_DCOM_OPEN_DT]
     ,mySource.[EM_LST_MOBILE_OPEN_DT]
     ,mySource.[EM_LST_SMRTPH_OPEN_DT]
     ,mySource.[EM_LST_TABLT_OPEN_DT]
     ,mySource.[EM_LST_CLICK_DT]
     ,mySource.[EM_LST_DCOM_CLICK_DT]
     ,mySource.[EM_LST_MOBILE_CLICK_DT]
     ,mySource.[EM_LST_SMRTPH_CLICK_DT]
     ,mySource.[EM_LST_TABLT_CLICK_DT]
     ,mySource.[WEB_LST_VST_DT]
     ,mySource.[APP_LST_VST_DT]
     ,mySource.[FANTASY_LST_VST_DT]
     ,mySource.[LST_M_FANTASY_VST_DT]
     ,mySource.[CURR_SSN_WEB_PAGEVIEWS]
     ,mySource.[CURR_SSN_FANTASY_PAGEVIEWS]
     ,mySource.[CURR_SSN_APP_VISITS]
     ,mySource.[CURR_SSN_M_FANTASY_PAGEVIEWS]
     ,mySource.[PREV_SSN_WEB_PAGEVIEWS]
     ,mySource.[PREV_SSN_FANTASY_PAGEVIEWS]
     ,mySource.[PREV_SSN_APP_VISITS]
     ,mySource.[PREV_SSN_M_FANTASY_PAGEVIEWS]
     ,mySource.[TOTAL_SSN_WEB_PAGEVIEWS]
     ,mySource.[TOTAL_CURR_SSN_FANTASY_PAGEVW]
     ,mySource.[TOTAL_CURR_SSN_APP_VISITS]
     ,mySource.[TOTAL_CURR_SSN_M_FANT_PAGEVW]
     ,mySource.[LST_CLUBS_STH_SSN]
     ,mySource.[LST_CLUBS_STB_SSN]
     ,mySource.[CLUBS_STB_TIX_REV]
     ,mySource.[CLUBS_STB_TIX_ORDERS]
     ,mySource.[CLUBS_STB_TIX_LST_DT]
     ,mySource.[CLUBS_STB_NUMSEATS]
     ,mySource.[LST_TICKET_EXCH_SSN]
     ,mySource.[TICKET_EXCH_REV]
     ,mySource.[TICKET_EXCH_ORDERS]
     ,mySource.[TICKET_EXCH_LST_DT]
     ,mySource.[TICKET_EXCH_NUMSEATS]
     ,mySource.[DTV_SUNDAY_TICKET_FLG]
     ,mySource.[DTV_SUNDAY_TICKET_ACTIVE_FLG]
     ,mySource.[DTV_TV_FLG]
     ,mySource.[DTV_TV_ACTIVE_FLG]
     ,mySource.[DTV_COMMERICAL_FLG]
     ,mySource.[DTV_COMMERICAL_ACTIVE_FLG]
     ,mySource.[MADDEN_PLAYER_FLG]
     ,mySource.[NFLN_SURVEY_HAVE_FLG]
     ,mySource.[NFLN_SURVEY_AWARE_FLG]
     ,mySource.[GIGYA_FLG]
     ,mySource.[SOCIAL_FACEBOOK_FLG]
     ,mySource.[SOCIAL_GOOGLEPLUS_FLG]
     ,mySource.[SOCIAL_MESSENGER_FLG]
     ,mySource.[TRANSACTIONAL_VALUE]
     ,mySource.[TRANSACTIONAL_VALUE_CURR_SSN]
     ,mySource.[TRANSACTIONAL_VALUE_PREV_SSN]
     ,mySource.[EPS_CRTD_DT]
FROM #SrcData AS mySource
LEFT JOIN ods.FanCentric_Customers AS myTarget
ON myTarget.CUST_ID = mySource.CUST_ID
WHERE myTarget.CUST_ID IS NULL;
;


EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Merge Statement Execution', 'Complete', @ExecutionId

DECLARE @MergeInsertRowCount int = ISNULL((SELECT CONVERT(varchar, COUNT(*)) FROM ods.FanCentric_Customers WHERE ETL_CreatedDate >= @RunTime AND ETL_UpdatedDate = ETL_CreatedDate),'0');	
DECLARE @MergeUpdateRowCount int = ISNULL((SELECT CONVERT(varchar, COUNT(*)) FROM ods.FanCentric_Customers WHERE ETL_UpdatedDate >= @RunTime AND ETL_UpdatedDate > ETL_CreatedDate),'0');	

EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Merge Insert Row Count', @MergeInsertRowCount, @ExecutionId
EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Merge Update Row Count', @MergeUpdateRowCount, @ExecutionId


END TRY 
BEGIN CATCH 

	DECLARE @ErrorMessage nvarchar(4000) = ERROR_MESSAGE();
	DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
	DECLARE @ErrorState INT = ERROR_STATE();
			
	PRINT @ErrorMessage
	EXEC etl.LogEventRecordDB @Batchid, 'Error', @ProcedureName, 'Merge Load', 'Merge Error', @ErrorMessage, @ExecutionId
	EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Procedure Processing', 'Complete', @ExecutionId

	RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState)

END CATCH

EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Procedure Processing', 'Complete', @ExecutionId


END





GO
