CREATE TABLE [adhoc].[Merch_Order_QA_2016_09_12]
(
[Id] [int] NULL,
[OrderGuid] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StoreId] [smallint] NULL,
[CustomerId] [int] NULL,
[BillingAddressId] [int] NULL,
[ShippingAddressId] [int] NULL,
[PickUpInStore] [smallint] NULL,
[OrderStatusId] [smallint] NULL,
[ShippingStatusId] [smallint] NULL,
[PaymentStatusId] [smallint] NULL,
[PaymentMethodSystemName] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerCurrencyCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrencyRate] [smallint] NULL,
[CustomerTaxDisplayTypeId] [smallint] NULL,
[VatNumber] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderSubtotalInclTax] [real] NULL,
[OrderSubtotalExclTax] [real] NULL,
[OrderSubTotalDiscountInclTax] [real] NULL,
[OrderSubTotalDiscountExclTax] [real] NULL,
[OrderShippingInclTax] [real] NULL,
[OrderShippingExclTax] [real] NULL,
[PaymentMethodAdditionalFeeInclTax] [smallint] NULL,
[PaymentMethodAdditionalFeeExclTax] [smallint] NULL,
[TaxRates] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderTax] [real] NULL,
[OrderDiscount] [real] NULL,
[OrderTotal] [real] NULL,
[RefundedAmount] [real] NULL,
[RewardPointsWereAdded] [smallint] NULL,
[CheckoutAttributeDescription] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CheckoutAttributesXml] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerLanguageId] [smallint] NULL,
[AffiliateId] [smallint] NULL,
[CustomerIp] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowStoringCreditCardNumber] [smallint] NULL,
[CardType] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardNumber] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaskedCreditCardNumber] [varchar] (56) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardCvv2] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardExpirationMonth] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardExpirationYear] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorizationTransactionId] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorizationTransactionCode] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorizationTransactionResult] [varchar] (49) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CaptureTransactionId] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CaptureTransactionResult] [varchar] (49) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubscriptionTransactionId] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaidDateUtc] [datetime] NULL,
[ShippingMethod] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShippingRateComputationMethodSystemName] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomValuesXml] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Deleted] [smallint] NULL,
[CreatedOnUtc] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastTimeStamp] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
