CREATE TABLE [dbo].[cleandataoutput_errorMiddleStep]
(
[BatchId] [bigint] NULL,
[ContactId] [varchar] (228) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactStatusCode] [bigint] NULL,
[ContactStatus] [varchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceContactId] [varchar] (108) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prefix] [varchar] (78) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (210) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (210) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salutation] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [varchar] (162) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suite] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (210) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZipCode] [varchar] (42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Plus4] [bigint] NULL,
[AddressCounty] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressCountry] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressCountyFips] [bigint] NULL,
[AddressType] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressDeliveryPoint] [bigint] NULL,
[ZipLatitude] [float] NULL,
[ZipLongitude] [float] NULL,
[AreaCode] [bigint] NULL,
[Phone] [varchar] (144) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneExtension] [varchar] (54) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmailAddress] [varchar] (432) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameStatus] [varchar] (258) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressStatus] [varchar] (168) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneStatus] [varchar] (42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmailStatus] [varchar] (162) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Prefix] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_FirstName] [varchar] (234) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_MiddleName] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_LastName] [varchar] (480) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Suffix] [varchar] (78) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_FullName] [varchar] (504) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_AddressType] [varchar] (84) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Address] [varchar] (1536) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Address2] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_City] [varchar] (210) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_State] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_ZipCode] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_AddressCounty] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_AddressCountry] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_PhoneType] [varchar] (72) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone] [varchar] (144) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_EmailType] [varchar] (72) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Email] [varchar] (432) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_SourcePriorityRank] [bigint] NULL,
[Input_SourceCreateDate] [datetime] NULL,
[Input_Custom1] [varchar] (108) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Custom2] [varchar] (42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Custom3] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Custom4] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Custom5] [bigint] NULL,
[RunContactMatch] [bit] NULL,
[Input_SourceSystem] [varchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ncoaAddress] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ncoaAddress2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ncoaSuite] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ncoaCity] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ncoaState] [varchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ncoaZipCode] [varchar] (42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ncoaPlus4] [bigint] NULL,
[ncoaAddressCounty] [varchar] (126) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ncoaAddressCountry] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ncoaAddressCountyFips] [bigint] NULL,
[ncoaAddressType] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ncoaAddressDeliveryPoint] [bigint] NULL,
[ncoaZipLatitude] [float] NULL,
[ncoaZipLongitude] [float] NULL,
[ncoaMoveEffectiveDate] [datetime] NULL
)
GO
