CREATE TABLE [ods].[Merch_Order]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NOT NULL,
[ETL_UpdatedDate] [datetime] NOT NULL,
[ETL_IsDeleted] [bit] NOT NULL,
[ETL_DeletedDate] [datetime] NULL,
[ETL_DeltaHashKey] [binary] (32) NULL,
[Id] [int] NOT NULL,
[AffiliateId] [int] NULL,
[Deleted] [bit] NULL,
[CreatedOnUtc] [datetime] NULL,
[LastTimeStamp] [binary] (8) NULL,
[OrderGuid] [uniqueidentifier] NULL,
[StoreId] [int] NULL,
[CustomerId] [int] NULL,
[BillingAddressId] [int] NULL,
[ShippingAddressId] [int] NULL,
[PickUpInStore] [bit] NULL,
[OrderStatusId] [int] NULL,
[ShippingStatusId] [int] NULL,
[PaymentStatusId] [int] NULL,
[PaymentMethodSystemName] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerCurrencyCode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrencyRate] [numeric] (18, 8) NULL,
[CustomerTaxDisplayTypeId] [int] NULL,
[VatNumber] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderSubtotalInclTax] [numeric] (18, 4) NULL,
[OrderSubtotalExclTax] [numeric] (18, 4) NULL,
[OrderSubTotalDiscountInclTax] [numeric] (18, 4) NULL,
[OrderSubTotalDiscountExclTax] [numeric] (18, 4) NULL,
[OrderShippingInclTax] [numeric] (18, 4) NULL,
[OrderShippingExclTax] [numeric] (18, 4) NULL,
[PaymentMethodAdditionalFeeInclTax] [numeric] (18, 4) NULL,
[PaymentMethodAdditionalFeeExclTax] [numeric] (18, 4) NULL,
[TaxRates] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderTax] [numeric] (18, 4) NULL,
[OrderDiscount] [numeric] (18, 4) NULL,
[OrderTotal] [numeric] (18, 4) NULL,
[RefundedAmount] [numeric] (18, 4) NULL,
[RewardPointsWereAdded] [bit] NULL,
[CheckoutAttributeDescription] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CheckoutAttributesXml] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerLanguageId] [int] NULL,
[CustomerIp] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowStoringCreditCardNumber] [bit] NULL,
[CardType] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardName] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardNumber] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaskedCreditCardNumber] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardCvv2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardExpirationMonth] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardExpirationYear] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorizationTransactionId] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorizationTransactionCode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorizationTransactionResult] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CaptureTransactionId] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CaptureTransactionResult] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubscriptionTransactionId] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaidDateUtc] [datetime] NULL,
[ShippingMethod] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShippingRateComputationMethodSystemName] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomValuesXml] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
CREATE NONCLUSTERED INDEX [IDX_MerchOrder_CustomerId] ON [ods].[Merch_Order] ([CustomerId])
GO
