CREATE TABLE [ods].[Snapshot_Nav_SalesHeader]
(
[Nav_SalesHeaderSK] [int] NOT NULL IDENTITY(1, 1),
[No] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YourReference] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipToName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipToName2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipToAddress] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipToAddress2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipToCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipToContact] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderDate] [datetime] NULL,
[ShipmentDate] [datetime] NULL,
[ShipmentMethodCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NAVAmount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NAVAmountIncludingVAT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SellToCustomerName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SellToCustomerName2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SellToAddress] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SellToAddress2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SellToCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SellToContact] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SellToPostCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SellToState] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SellToCountryRegionCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipToPostCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipToState] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipToCountryRegionCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaymentMethodCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShippingAgentCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncrementID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderID] [int] NULL,
[AppliedRuleIDs] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StagingTransEntryNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerGroupID] [int] NULL,
[Email] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EntityNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount] [numeric] (18, 2) NULL,
[TaxAmount] [numeric] (18, 2) NULL,
[TotalAmount] [numeric] (18, 2) NULL,
[DiscountAmount] [numeric] (18, 2) NULL,
[ShippingAmount] [numeric] (18, 2) NULL,
[ETL_CreatedOn] [datetime] NULL,
[ETL_CreatedBy] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_UpdatedOn] [datetime] NULL,
[ETL_UpdatedBy] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecordEndDate] [datetime] NULL
)
GO
ALTER TABLE [ods].[Snapshot_Nav_SalesHeader] ADD CONSTRAINT [PK__Snapshot__33E43829A4DD6F32] PRIMARY KEY CLUSTERED  ([Nav_SalesHeaderSK])
GO
