CREATE TABLE [rpt].[PreCache_Cust_Merch_2_tbl]
(
[DataType] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SaleMonth] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STH_Rev] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH_Cnt] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH_Items] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH_Avg] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Waitlist_Rev] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Waitlist_Cnt] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Waitlist_Items] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Waitlist_Avg] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SG_Rev] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SG_Cnt] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SG_Items] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SG_Avg] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SNU_Rev] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SNU_Cnt] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SNU_Items] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SNU_Avg] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsSnuNon_SNU_Rev] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Non_SNU_Cnt] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Non_SNU_Items] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Non_SNU_Avg] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Digest_Rev] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Digest_Cnt] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Digest_Items] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Digest_Avg] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[In_Market_Rev] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[In_Market_Cnt] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[In_Market_Items] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[In_Market_Avg] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Out_of_Market_Rev] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Out_of_Market_Cnt] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Out_of_Market_Items] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Out_of_Market_Avg] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[New_Buyer_Rev] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[New_Cnt] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[New_Buyer_Items] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[New_Buyer_Avg] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Repeat_Buyer_Rev] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Repeat_Cnt] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Repeat_Buyer_Items] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Repeat_Buyer_Avg] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Orders] [int] NULL,
[TotalRevenue] [numeric] (38, 4) NULL,
[UniqueBuyers] [int] NULL,
[isReady] [int] NOT NULL
)
GO
