CREATE TABLE [rpt].[PreCache_Cust_Email_12_tbl]
(
[SortOrder] [int] NULL,
[Month] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Members_Newsletter] [int] NULL,
[Members_Snu] [int] NULL,
[Members_Merch] [int] NULL,
[Members_Partner_offers] [int] NULL,
[Members_Heinz_field] [int] NULL,
[Members_Team_events] [int] NULL,
[Members_Concerts] [int] NULL,
[Members_Total] [int] NULL,
[Adds_Newsletter] [int] NULL,
[Adds_Snu] [int] NULL,
[Adds_Merch] [int] NULL,
[Adds_Partner_offers] [int] NULL,
[Adds_Heinz_field] [int] NULL,
[Adds_Team_events] [int] NULL,
[Adds_Concerts] [int] NULL,
[Adds_Total] [int] NULL,
[Count_Newsletter] [int] NULL,
[Count_Snu] [int] NULL,
[Count_Merch] [int] NULL,
[Count_Partner_offers] [int] NULL,
[Count_Heinz_field] [int] NULL,
[Count_Team_events] [int] NULL,
[Count_Concerts] [int] NULL,
[Count_Total] [int] NULL,
[IsReady] [int] NOT NULL
)
GO
