CREATE TABLE [src].[Steelers_500f_customer_20160229]
(
[loyalty_id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[email] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[external_customer_id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[enrolled_at] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[first_name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[balance] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lifetime_balance] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_activity] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[unsubscribed] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[top_tier_name] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tier_join_date] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tier_expiration_date] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[birthdate] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address_2] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[city] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[country] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[postal_code] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mobile_phone] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[home_phone] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[work_phone] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[home_store] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[channel] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sub_channel] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sub_channel_detail] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[brand] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
