CREATE TABLE [src].[Merch_Category]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NOT NULL,
[LastTimeStamp] [binary] (8) NULL,
[Id] [int] NULL,
[Name] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShowOnHomePage] [bit] NULL,
[MetaKeywords] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MetaDescription] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MetaTitle] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubjectToAcl] [bit] NULL,
[LimitedToStores] [bit] NULL,
[HasDiscountsApplied] [bit] NULL,
[DisplayOrder] [int] NULL,
[Published] [bit] NULL,
[Deleted] [bit] NULL,
[CreatedOnUtc] [datetime] NULL,
[UpdatedOnUtc] [datetime] NULL,
[Description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryTemplateId] [int] NULL,
[ParentCategoryId] [int] NULL,
[PictureId] [int] NULL,
[PageSize] [int] NULL,
[AllowCustomersToSelectPageSize] [bit] NULL,
[PageSizeOptions] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceRanges] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncludeInTopMenu] [bit] NULL
)
GO
