CREATE TABLE [src].[Nav_SalesHeader]
(
[SK] [bigint] NULL,
[ETL__multi_query_value_for_audit] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L1_AllData_odata.metadata] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L2_AllData_value_] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[No] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YourReference] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShiptoName] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShiptoName2] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShiptoAddress] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShiptoAddress2] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShiptoCity] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShiptoContact] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderDate] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipmentDate] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipmentMethodCode] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NAVAmount] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NAVAmountIncludingVAT] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SelltoCustomerName] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SelltoCustomerName2] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SelltoAddress] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SelltoAddress2] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SelltoCity] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SelltoContact] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SelltoPostCode] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SelltoState] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SelltoCountryRegionCode] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShiptoPostCode] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShiptoState] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShiptoCountryRegionCode] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaymentMethodCode] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShippingAgentCode] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncrementID] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderID] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AppliedRuleIDs] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StagingTransEntryNo] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerGroupID] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMail] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EntityNo] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxAmount] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalAmount] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiscountAmount] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShippingAmount] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L3_AllData_value_ETag] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
