CREATE TABLE [src].[Merch_tbl_Reg_User]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NOT NULL,
[ID] [int] NULL,
[UserName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[servicePlanID] [smallint] NULL,
[serviceStatusID] [smallint] NULL,
[Password] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthCode] [smallint] NULL,
[FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressID] [int] NULL,
[shippingAddressID] [int] NULL,
[shippingMethodID] [int] NULL,
[paymentID] [int] NULL,
[Marketing] [bit] NULL,
[date_Start] [datetime] NULL,
[Score] [int] NULL,
[Posts] [int] NULL,
[shareEmail] [bit] NULL,
[shareLocation] [bit] NULL,
[sendCatalog] [bit] NULL,
[suspended] [bit] NULL,
[deleted] [bit] NULL,
[birthdate] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailBrowserTypeID] [int] NULL,
[emailContentType] [tinyint] NULL,
[shareInfo] [bit] NULL,
[address1] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[city] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zip] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailStatus] [tinyint] NULL,
[hostID] [int] NULL,
[emailSent] [smallint] NULL,
[emailOpened] [smallint] NULL,
[emailClicks] [smallint] NULL,
[integration] [bit] NULL,
[mBoardAccount] [tinyint] NULL,
[mBoardStatus] [tinyint] NULL,
[pageSize] [smallint] NULL,
[avatar] [smallint] NULL,
[recentFirst] [bit] NULL,
[timeZone] [tinyint] NULL,
[mBoardMessage] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bio] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[favoritePlayer] [smallint] NULL,
[attendedGame] [bit] NULL,
[gender] [bit] NULL,
[informOffers] [bit] NULL,
[seasonTicketHolder] [bit] NULL,
[cardType] [int] NULL,
[cardHolder] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cardNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cardMonth] [tinyint] NULL,
[cardYear] [smallint] NULL,
[cardZipCode] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billingAgree] [tinyint] NULL,
[num1] [tinyint] NULL
)
GO
