CREATE TABLE [src].[Merch_Product]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NOT NULL,
[LastTimeStamp] [binary] (8) NULL,
[Id] [int] NULL,
[ProductTypeId] [int] NULL,
[ParentGroupedProductId] [int] NULL,
[VisibleIndividually] [bit] NULL,
[Name] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShortDescription] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FullDescription] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdminComment] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductTemplateId] [int] NULL,
[VendorId] [int] NULL,
[ShowOnHomePage] [bit] NULL,
[MetaKeywords] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MetaDescription] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MetaTitle] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowCustomerReviews] [bit] NULL,
[ApprovedRatingSum] [int] NULL,
[NotApprovedRatingSum] [int] NULL,
[ApprovedTotalReviews] [int] NULL,
[NotApprovedTotalReviews] [int] NULL,
[SubjectToAcl] [bit] NULL,
[LimitedToStores] [bit] NULL,
[Sku] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ManufacturerPartNumber] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gtin] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsGiftCard] [bit] NULL,
[GiftCardTypeId] [int] NULL,
[RequireOtherProducts] [bit] NULL,
[RequiredProductIds] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AutomaticallyAddRequiredProducts] [bit] NULL,
[IsDownload] [bit] NULL,
[DownloadId] [int] NULL,
[UnlimitedDownloads] [bit] NULL,
[MaxNumberOfDownloads] [int] NULL,
[DownloadExpirationDays] [int] NULL,
[DownloadActivationTypeId] [int] NULL,
[HasSampleDownload] [bit] NULL,
[SampleDownloadId] [int] NULL,
[HasUserAgreement] [bit] NULL,
[UserAgreementText] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsRecurring] [bit] NULL,
[RecurringCycleLength] [int] NULL,
[RecurringCyclePeriodId] [int] NULL,
[RecurringTotalCycles] [int] NULL,
[IsRental] [bit] NULL,
[RentalPriceLength] [int] NULL,
[RentalPricePeriodId] [int] NULL,
[IsShipEnabled] [bit] NULL,
[IsFreeShipping] [bit] NULL,
[ShipSeparately] [bit] NULL,
[AdditionalShippingCharge] [numeric] (18, 4) NULL,
[DeliveryDateId] [int] NULL,
[IsTaxExempt] [bit] NULL,
[TaxCategoryId] [int] NULL,
[IsTelecommunicationsOrBroadcastingOrElectronicServices] [bit] NULL,
[ManageInventoryMethodId] [int] NULL,
[UseMultipleWarehouses] [bit] NULL,
[WarehouseId] [int] NULL,
[StockQuantity] [int] NULL,
[DisplayStockAvailability] [bit] NULL,
[DisplayStockQuantity] [bit] NULL,
[MinStockQuantity] [int] NULL,
[LowStockActivityId] [int] NULL,
[NotifyAdminForQuantityBelow] [int] NULL,
[BackorderModeId] [int] NULL,
[AllowBackInStockSubscriptions] [bit] NULL,
[OrderMinimumQuantity] [int] NULL,
[OrderMaximumQuantity] [int] NULL,
[AllowedQuantities] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowAddingOnlyExistingAttributeCombinations] [bit] NULL,
[DisableBuyButton] [bit] NULL,
[DisableWishlistButton] [bit] NULL,
[AvailableForPreOrder] [bit] NULL,
[PreOrderAvailabilityStartDateTimeUtc] [datetime] NULL,
[CallForPrice] [bit] NULL,
[Price] [numeric] (18, 4) NULL,
[OldPrice] [numeric] (18, 4) NULL,
[ProductCost] [numeric] (18, 4) NULL,
[SpecialPrice] [numeric] (18, 4) NULL,
[SpecialPriceStartDateTimeUtc] [datetime] NULL,
[SpecialPriceEndDateTimeUtc] [datetime] NULL,
[CustomerEntersPrice] [bit] NULL,
[MinimumCustomerEnteredPrice] [numeric] (18, 4) NULL,
[MaximumCustomerEnteredPrice] [numeric] (18, 4) NULL,
[HasTierPrices] [bit] NULL,
[HasDiscountsApplied] [bit] NULL,
[Weight] [numeric] (18, 4) NULL,
[Length] [numeric] (18, 4) NULL,
[Width] [numeric] (18, 4) NULL,
[Height] [numeric] (18, 4) NULL,
[AvailableStartDateTimeUtc] [datetime] NULL,
[AvailableEndDateTimeUtc] [datetime] NULL,
[DisplayOrder] [int] NULL,
[Published] [bit] NULL,
[Deleted] [bit] NULL,
[CreatedOnUtc] [datetime] NULL,
[UpdatedOnUtc] [datetime] NULL,
[Video] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SizeChartId] [int] NULL,
[AvailabilityId] [int] NULL
)
GO
