CREATE TABLE [stg].[Epsilon_Activities_CustomerSummary]
(
[ETL_CreatedDate] [datetime] NOT NULL,
[CustomerKey] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumDelivered_BREAKINGNEWS] [int] NULL,
[NumClicked_BREAKINGNEWS] [int] NULL,
[NumOpened_BREAKINGNEWS] [int] NULL,
[NumDelivered_HF] [int] NULL,
[NumClicked_HF] [int] NULL,
[NumOpened_HF] [int] NULL,
[NumDelivered_MERCH] [int] NULL,
[NumClicked_MERCH] [int] NULL,
[NumOpened_MERCH] [int] NULL,
[NumDelivered_MKTG] [int] NULL,
[NumClicked_MKTG] [int] NULL,
[NumOpened_MKTG] [int] NULL,
[NumDelivered_NEWS] [int] NULL,
[NumClicked_NEWS] [int] NULL,
[NumOpened_NEWS] [int] NULL,
[NumDelivered_REACTIVATION] [int] NULL,
[NumClicked_REACTIVATION] [int] NULL,
[NumOpened_REACTIVATION] [int] NULL,
[NumDelivered_SNU] [int] NULL,
[NumClicked_SNU] [int] NULL,
[NumOpened_SNU] [int] NULL,
[NumDelivered_SPONSOR] [int] NULL,
[NumClicked_SPONSOR] [int] NULL,
[NumOpened_SPONSOR] [int] NULL
)
GO
