IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SSBCLOUD\gholder')
CREATE LOGIN [SSBCLOUD\gholder] FROM WINDOWS
GO
CREATE USER [SSBCLOUD\gholder] FOR LOGIN [SSBCLOUD\gholder] WITH DEFAULT_SCHEMA=[SSBCLOUD\gholder]
GO
REVOKE CONNECT TO [SSBCLOUD\gholder]
